# Generated by Django 5.2 on 2025-05-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание блога",
                max_length=1000,
                null=True,
                verbose_name="Содержимое",
            ),
        ),
    ]
