# Generated by Django 5.2 on 2025-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                help_text="Введите наименование продукта",
                max_length=50,
                verbose_name="Наименование",
            ),
        ),
    ]
